export const galleryImages: string[] = [
  "/images/carousel/nagoya-main-room.jpeg",
  "/images/carousel/nagoya-full-room.jpeg",
  "/images/carousel/nagoya-bear-decoration.jpeg",
  "/images/carousel/nagoya-play-area.jpeg",
  "/images/carousel/nagoya-kitchen-area.jpeg",
  "/images/carousel/nagoya-party-setup.jpeg",
  "/images/carousel/nagoya-sofa-area.jpeg",
  "/images/carousel/nagoya-toys-display.jpeg",
  "/images/carousel/nagoya-children-playing.jpeg",
  "/images/carousel/nagoya-birthday-party.jpeg",
  "/images/carousel/nagoya-dining-setup.jpeg",
  "/images/carousel/nagoya-projector-area.jpeg",
  "/images/carousel/nagoya-baby-area.jpeg",
  "/images/carousel/nagoya-wide-space.jpeg",
  "/images/carousel/nagoya-natural-light.jpeg",
]
